site:
  robots: allow
  start_page: online-guides::index.adoc
  title: hobex Online Guides
  url: https://guides.qenta.com
content:
  edit_url: ~
  sources:
    - url: ./
      branches: HEAD
      start_paths:
        - content/*
runtime:
  cache_dir: ./build/cache
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./ui-customizations/supplemental_ui
urls:
  html_extension_style: indexify
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
